# GET http://localhost:3000/users HTTP/1.1
# X-Tenant-ID: cmhxt6zmt0001x520yqu0p8e8

# POST http://localhost:3000/auth/signup



POST http://localhost:3000/auth/test-login
Content-Type: application/json

{
  "email": "rafa@gmail.com",
  "name": "Rafael",
  "provider": "google",
  "providerId": "google-uid-123"
}


